language: node_js
node_js:  stable
install:  npm install --no-optional
script:   ./node_modules/.bin/gulp ci
after_script:
  - npm install codeclimate-test-reporter
  - codeclimate-test-reporter < ./build/coverage/lcov.info
